### ISSUE TITLE
v2.0.0 Roadmap

### ISSUE THREAD

**Issue by jdkato** [vale-cli/vale#142]
I'd like to start thinking about the goals for the next major release of Vale, with an emphasis on improving format support and configuration handling. Feel free to comment or make suggestions.

## New Features

- [x] XML support (#114)
    - [x] [DITA Open Toolkit](https://www.dita-ot.org/)
    - [x] [`xsltproc`](http://xmlsoft.org/XSLT/xsltproc.html)
- [x] Debug mode (#144)
- [x] Expanded scopes: `code`, `bold`, `italic`, etc.

## Bug Fixes

- [x] #140 
- [x] #119 

## Docs

- [x] #80
